var levelUpStats = {
    "Tongarango": {
        atk: 4,
        def: 4,
        maxHP: 5,
        maxPP: 3,
        agl: 3,
        evd: 1,
        ability: {"Tremor": 1, "Resuscitate": 3, "Dynamite": 5, "Sumo Finish Flop": 20},
    },
    "Nels": {
        atk: 4,
        def: 1.5,
        maxHP: 3,
        maxPP: 5,
        agl: 5,
        evd: 3,
        ability: {"Finis": 1, "Venegance": 3, "Dynamis": 5, "Shield Breaker": 7, "Swath": 15, "Pentimone": 20},
    },
    "Tux": {
        atk: 3,
        def: 2,
        maxHP: 3,
        maxPP: 4,
        agl: 4,
        evd: 2,
        ability: {"Finis": 1},
    },
    "Goat": {
        atk: 2,
        def: 2,
        maxHP: 4,
        maxPP: 3,
        agl: 2,
        evd: 1,
        ability: {"Burrito": 1, "Horn": 5, "Poison Flauta": 1},
    },
    "Sam": {
        atk: 3,
        def: 2,
        maxHP: 4,
        maxPP: 3,
        agl: 4,
        evd: 1.5,
        ability: {"Bench Press": 1, "Cross Bones": 1, "Ear Jets": 1},
    },
    "Flam": {
        atk: 2,
        def: 1,
        maxHP: 3,
        maxPP: 5,
        agl: 5,
        evd: 2,
        ability: {"Bench Press": 1, "Cross Bones": 1, "Ear Jets": 1},
    },
    "Willoughby": {
        atk: 3.5,
        def: 2,
        maxHP: 4,
        maxPP: 4,
        agl: 4,
        evd: 2.5,
        ability: {"Finis": 1, "Quicken": 3, "Semper Fi": 5, "Disarm": 7, "Exeunt": 15, "Triforce": 20},
    },
}